# Generated by Django 3.2.6 on 2021-09-19 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fashionz', '0009_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1-Very Dissatisfied'), (2, '2-Dissatisfied'), (3, '3-Fair'), (4, '4-Satisfied'), (5, '5-Very Satisfied')], max_length=50, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='fashionz.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
